# Generated by Django 4.1 on 2023-06-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_category_user_dayssale_user_solditem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='unit_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
