# Generated by Django 4.1 on 2023-07-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0002_dayssale_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Momo', 'Momo'), ('Card', 'Card')], default='Cash', max_length=100),
        ),
    ]
