# Generated by Django 4.1 on 2023-06-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0003_cart_total_price_cart_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayssale',
            name='sale_reference',
            field=models.CharField(default='cook', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solditem',
            name='sale_reference',
            field=models.CharField(default='cook', max_length=200),
            preserve_default=False,
        ),
    ]
