# Generated by Django 4.1 on 2023-07-05 10:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pos_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_alter_customuser_role_alter_individualdaysale_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=pos_app.models.get_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='has_cashier',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='shop_contact',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='shop_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='shop_receipt_generation_prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='individualdaysale',
            name='day',
            field=models.DateField(default=datetime.date(2023, 7, 5)),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.CreateModel(
            name='CashierCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('domain', models.CharField(max_length=250)),
                ('product_qty', models.PositiveIntegerField()),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_app.product')),
                ('user', models.ForeignKey(default=pos_app.models.get_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
