# Generated by Django 4.1 on 2023-06-18 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_dayssale_sale_reference_solditem_sale_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayssale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dayssale',
            name='customer_phone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solditem',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solditem',
            name='customer_phone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualdaysale',
            name='day',
            field=models.DateField(default=datetime.date(2023, 6, 18)),
        ),
    ]
