# Generated by Django 4.1 on 2023-07-04 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pos_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_product_cost_price_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=pos_app.models.get_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='has_cashier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='shop_contact',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='shop_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='shop_receipt_generation_prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
