# Generated by Django 4.1 on 2023-07-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0004_alter_customuser_role_alter_individualdaysale_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
