# Generated by Django 4.1 on 2023-06-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0005_dayssale_customer_name_dayssale_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayssale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='customer_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='customer_phone',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
