# Generated by Django 4.1 on 2023-06-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0006_alter_dayssale_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayssale',
            name='amount_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dayssale',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solditem',
            name='amount_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solditem',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
