# Generated by Django 4.1 on 2023-07-08 19:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0006_cashiercart'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='cashiercart',
        #     name='created_at',
        #     field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='individualdaysale',
            name='day',
            field=models.DateField(default=datetime.date(2023, 7, 8)),
        ),
    ]
