# Generated by Django 4.1 on 2023-07-10 20:14

from django.db import migrations, models
import django.db.models.deletion
import pos_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0008_remove_dayssale_amount_paid_remove_dayssale_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayssale',
            name='sale',
            field=models.ForeignKey(default=pos_app.models.get_sale, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_app.daysaleorder'),
        ),
        migrations.AddField(
            model_name='solditem',
            name='sale',
            field=models.ForeignKey(default=pos_app.models.get_sold, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='pos_app.soldorder'),
        ),
        migrations.AlterField(
            model_name='daysaleorder',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
