# Generated by Django 4.1 on 2023-07-11 07:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pos_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0009_dayssale_sale_alter_daysaleorder_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solditem',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='solditem',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='solditem',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='solditem',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='solditem',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='solditem',
            name='user',
        ),
        migrations.AlterField(
            model_name='individualdaysale',
            name='day',
            field=models.DateField(default=datetime.date(2023, 7, 11)),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='closed_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SoldOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=250)),
                ('sale_reference', models.CharField(max_length=200)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Momo', 'Momo'), ('Card', 'Card')], default='Cash', max_length=100)),
                ('discount', models.CharField(blank=True, max_length=100, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # migrations.AddField(
        #     model_name='solditem',
        #     name='sale',
        #     field=models.ForeignKey(default=pos_app.models.get_sold, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_app.soldorder'),
        # ),
    ]
