# Generated by Django 4.2.4 on 2023-12-12 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import pos_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0010_remove_solditem_amount_paid_remove_solditem_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualdaysale',
            name='day',
            field=models.DateField(default=datetime.date(2023, 12, 12)),
        ),
    ]
