# Generated by Django 4.2.4 on 2023-12-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0011_solditem_sale_alter_individualdaysale_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldorder',
            name='closed_date',
            field=models.DateField(null=True),
        ),
    ]
