# Generated by Django 4.1 on 2023-06-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0012_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='restockhistory',
            name='previous_quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
