# Generated by Django 4.2.4 on 2023-12-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0012_alter_soldorder_closed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldorder',
            name='closed_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
