# Generated by Django 4.1 on 2023-06-25 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0013_restockhistory_previous_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualdaysale',
            name='day',
            field=models.DateField(default=datetime.date(2023, 6, 25)),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S/S', 'S/S'), ('Q/S', 'Q/S'), ('M/S', 'M/S'), ('A/S', 'A/S'), ('B/S', 'B/S'), ('E/L', 'E/L')], max_length=200),
        ),
    ]
