# Generated by Django 5.1 on 2026-03-23 15:33

import datetime
import django.db.models.deletion
import pos_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0014_solditem_sale_alter_individualdaysale_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualdaysale',
            name='day',
            field=models.DateField(default=datetime.date(2026, 3, 23)),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='sale',
            field=models.ForeignKey(default=pos_app.models.get_sold, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos_app.soldorder'),
        ),
    ]
