# Generated by Django 4.1 on 2023-06-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_app', '0015_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S/S', 'S/S'), ('Q/S', 'Q/S'), ('M/S', 'M/S'), ('A/S', 'A/S'), ('B/S', 'B/S'), ('E/L', 'E/L')], max_length=200),
        ),
    ]
